### ISSUE TITLE
404  Страница не найдена

### ISSUE THREAD

**Issue by kesselshlosser** [Turbo-CMS/TurboShop#1]
404 Страница не найдена при попытке  перейти   на order/оформить заказ

**Comment by Turbo-CMS** [comment]
> 404 Страница не найдена при попытке перейти на order/оформить заказ
Проверил локально и на демке ошибка не наблюдается. Какие у вашего сервера параметры?

**Comment by kesselshlosser** [comment]
Openserver 5.3.8 php 7.3 mysql 8.0
