### ISSUE TITLE
site.com/contact

### ISSUE THREAD

**Issue by Ang8r2** [Turbo-CMS/TurboShop#10]
Where is this page located?!!!!!! I can't find in which section of the CMS to change the photo of damn Kiev as well as the address.

I also can't turn off motivational labels - Affordable prices for the best brands,Fast delivery within 24 hours, etc.
/turbo/index.php?module=BannersImagesAdmin - they are turned off here, but they are displayed on the site.

**Comment by Direg** [comment]
Design > Translations

design/turboshop/images/contacts.jpg

**Comment by Ang8r2** [comment]
I'm talking about the address superimposed on the photo. In which section is this setting located?

**Comment by Direg** [comment]
Design > Translations, the "office" variable.
