### ISSUE TITLE
How do I log in to the admin panel?

### ISSUE THREAD

**Issue by PozidoK** [Turbo-CMS/TurboShop#2]
How do I log in to the admin panel? by switching to /turbo? a link came to the mail. I enter the password and the new page does not load

**Comment by Turbo-CMS** [comment]
> How do I log in to the admin panel? by switching to /turbo? a link came to the mail. I enter the password and the new page does not load

Replace the file turbo/.passwd with the default one, the login for the admin panel will be login: admin, password: admin
