### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by Ang8r2** [Turbo-CMS/TurboShop#7]
after the welcome message, I get the error 403 Access Denied.
Changing file access rights does not solve the problem in any way.
http://site/install.php?lang=en&step=unzip
wtf?

**Comment by Turbo-CMS** [comment]
Without additional information, it is difficult to respond. The issue might
be related to the directory where you are installing. The error is likely
due to the .htaccess file. At the very bottom of the root .htaccess file,
there is code labeled # Security; try deleting it.
